---
name: CI
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    name: Run tests.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup just.
        uses: extractions/setup-just@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run tests.
        run: just test-docker
