executable_path := "./.build/release/examples"

build:
  @swift build -c release

run command="section": build
   @{{executable_path}} {{command}}

snapshot command="section" outputDir="${PWD}": build
  @freeze --execute "{{executable_path}} {{command}}" \
    --output {{outputDir}}/"{{command}}.png" \
    --width 500
